### PR TITLE
Uninstalling should change directory if in nix

### LINKED ISSUE #517: Uninstall step should changedirectory from `/nix` if it is there
I'm using an Intel iMac and recently updated to Ventura 13.4. At this point, I'm used to macOS updates wiping my nix settings. Normally I uninstall nix and reinstall it after macOS updates, but this time I messed up. What I did:

1. Updated macOS
2. `cd`ed into `/nix/` to run `nix-installer uninstall` 👈 I don't normally do this
3. `nix-installer` errored out because `zsh` was using the `/nix` volume
4. Now I can neither install or uninstall nix.

I'm unsure if the error stemmed from the fact that I `cd`'ed into `/nix` or if it was the version of the macOS update.

## Error

```
Error:+
+++0:+Error+reverting
+++0:+Action+`configure_nix`+errored
++++++Multiple+child+errors

++++++Action+`configure_shell_profile`+errored
++++++Multiple+child+errors

++++++Action+`create_or_insert_into_file`+errored
++++++Open+path+`/etc/bash.bashrc`

++++++Action+`create_or_insert_into_file`+errored
++++++Open+path+`/usr/local/share/fish/vendor_conf.d/nix.fish`

++++++Action+`create_directory`+errored
++++++Read+path+`/usr/local/share/fish/vendor_conf.d`


++++++Action+`place_nix_configuration`+errored
++++++Multiple+child+errors

++++++Action+`create_or_merge_nix_config`+errored
++++++Remove+file+`/etc/nix/nix.conf`

++++++Action+`create_directory`+errored
++++++Read+path+`/etc/nix`



++++++Action+`provision_nix`+errored
++++++Multiple+child+errors

++++++Action+`create_users_and_group`+errored
++++++Multiple+child+errors

++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld1"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld2"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld3"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld4"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld5"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld6"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld7"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld8"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld9"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld10"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld11"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld12"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld13"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld14"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld15"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld16"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld17"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld18"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld19"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld20"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld21"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld22"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld23"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld24"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld25"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld26"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld27"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld28"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld29"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld30"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld31"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_user`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Users/_nixbld32"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)



++++++Action+`create_group`+errored
++++++Failed+to+execute+command+with+status+185+`"/usr/bin/dscl"+"."+"-delete"+"/Groups/nixbld"`,+stdout:+delete:+Invalid+Path

++++++stderr:+<dscl_cmd>+DS+Error:+-14009+(eDSUnknownNodeName)




++++++Action+`create_directory`+errored
++++++Read+path+`/nix/var/nix/temproots`


++++++Action+`create_nix_volume`+errored
++++++Multiple+child+errors

++++++Action+`bootstrap_launchctl_service`+errored
++++++Failed+to+execute+command+with+status+2+`"launchctl"+"bootout"+"system"+"/Library/LaunchDaemons/org.nixos.darwin-store.plist"`,+stdout:+
++++++stderr:+/Library/LaunchDaemons/org.nixos.darwin-store.plist:+No+such+file+or+directory
++++++Boot-out+failed:+2:+No+such+file+or+directory



++++++Action+`create_volume_service`+errored
++++++Remove+file+`/Library/LaunchDaemons/org.nixos.darwin-store.plist`

++++++Action+`create_apfs_volume`+errored
++++++Failed+to+execute+command+with+status+1+`"/usr/sbin/diskutil"+"apfs"+"deleteVolume"+"Nix+Store"`,+stdout:+Started+APFS+operation
++++++Deleting+APFS+Volume+from+its+APFS+Container
++++++Unmounting+disk1s7
++++++The+volume+"Nix+Store"+on+disk1s7+couldn't+be+unmounted+because+it+is+in+use+by+process+0+(kernel)

++++++stderr:+Error:+-69888:+Couldn't+unmount+disk



++++++Action+`create_or_insert_into_file`+errored
++++++Open+path+`/etc/synthetic.conf`


```

## Metadata

|key|value|
|--|--|
|**version**|0.8.0|
|**os**|macos|
|**arch**|x86_64|

### PR DESCRIPTION
**Pull request by Hoverbear**
##### Description

Also includes a couple missed warnings from last PR (#524 )

Fixes #517 .

##### Checklist

- [ ] Formatted with `cargo fmt`
- [ ] Built with `nix build`
- [ ] Ran flake checks with `nix flake check`
- [ ] Added or updated relevant tests (leave unchecked if not applicable)
- [ ] Added or updated relevant documentation (leave unchecked if not applicable)
- [ ] Linked to related issues (leave unchecked if not applicable)

##### Validating with `install.determinate.systems`

If a maintainer has added the `upload to s3` label to this PR, it will become available for installation via `install.determinate.systems`:

```shell
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/$PR_NUMBER | sh -s -- install
```

### CODE REVIEW

File: src/action/common/provision_nix.rs [hunk 1]
```diff
@@ -1,10 +1,9 @@
-use nix::unistd::Group;
 use tracing::{span, Span};
 
-use super::{CreateNixTree, DeleteUsersInGroup};
```
Comment (cole-h) [inline src/action/common/provision_nix.rs:4]: Eh?

Comment (Hoverbear) [reply src/action/common/provision_nix.rs:4]: They were from #524...

Comment (cole-h) [reply src/action/common/provision_nix.rs:4]: Oh, they're  no longer necessary? Gotcha.

**Review by cole-h — APPROVED** [review]
