### PR TITLE
Nix config: add extra newlines after the initial comment

### LINKED ISSUE #717: `--extra-conf` doesn't add newline with some (all?) options
Given the following invocation of the installer:
```bash
$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/branch/main | sh -s -- install macos --no-confirm --extra-conf 'trusted-users = admin'
```

The generated Nix configuration file looks like:
```
# Generated by https://github.com/DeterminateSystems/nix-installer.
# See `/nix/nix-installer --version` for the version details.trusted-users = admin
build-users-group = nixbld
experimental-features = nix-command flakes repl-flake
bash-prompt-prefix = (nix:$name)\040
max-jobs = auto
extra-nix-path = nixpkgs=flake:nixpkgs
```

This would seemingly also cause the `sandbox = false` example in the README to not work.

### PR DESCRIPTION
**Pull request by grahamc**
Otherwise the extra-config option will get swallowed.
    
Closes #717

##### Checklist

- [ ] Formatted with `cargo fmt`
- [ ] Built with `nix build`
- [ ] Ran flake checks with `nix flake check`
- [ ] Added or updated relevant tests (leave unchecked if not applicable)
- [ ] Added or updated relevant documentation (leave unchecked if not applicable)
- [ ] Linked to related issues (leave unchecked if not applicable)

##### Validating with `install.determinate.systems`

If a maintainer has added the `upload to s3` label to this PR, it will become available for installation via `install.determinate.systems`:

```shell
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/$PR_NUMBER | sh -s -- install
```

### CODE REVIEW

File: src/action/base/create_or_merge_nix_config.rs [hunk 1]
```diff
@@ -413,6 +413,8 @@ impl Action for CreateOrMergeNixConfig {
             &[
                 "# Generated by https://github.com/DeterminateSystems/nix-installer.",
                 "# See `/nix/nix-installer --version` for the version details.",
```
Comment (cole-h) [inline src/action/base/create_or_merge_nix_config.rs:415]: IMHO it would be better to do `new_config.push_str("# Generated by.....\n"); new_config.push_str("# See ........\n");` rather than just splatting in some more newlines.

Comment (grahamc) [reply src/action/base/create_or_merge_nix_config.rs]: Good idea, I updated!

File: src/action/base/create_or_merge_nix_config.rs [hunk 2]
```diff
@@ -409,13 +409,10 @@ impl Action for CreateOrMergeNixConfig {
...
-            &[
-                "# Generated by https://github.com/DeterminateSystems/nix-installer.",
-                "# See `/nix/nix-installer --version` for the version details.",
-            ]
-            .join("\n"),
-        );
+        new_config
+            .push_str("# Generated by https://github.com/DeterminateSystems/nix-installer.\n");
+        new_config.push_str("# See `/nix/nix-installer --version` for the version details.\n");
+        new_config.push_str("\n");
```
Comment (cole-h) [inline src/action/base/create_or_merge_nix_config.rs:415]: I don't think this final newline is necessary. Configs will look like

```
# Generated by https://github.com/DeterminateSystems/nix-installer.
# See `/nix/nix-installer --version` for the version details.

config-here
```

rather than 

```
# Generated by https://github.com/DeterminateSystems/nix-installer.
# See `/nix/nix-installer --version` for the version details.
config-here
```

It doesn't really matter at the end of the day, but I myself prefer the second over the first.

**Review by cole-h — APPROVED** [review]

File: src/action/base/create_or_merge_nix_config.rs (hunk 2 above)
Comment (grahamc) [reply src/action/base/create_or_merge_nix_config.rs:415]: I like it aesthetically so lets just roll with it hah

**Review by Hoverbear — APPROVED** [review]
